image: docker

variables:
    IMAGE: "fatihdemirci/reactdeployment"
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""
    AWS_DEFAULT_REGION: 'eu-south-1'
    ECS_SERVICE: 'reactApp-ecs-service'
    ECS_CLUSTER: 'reactApp-ecs-cluster'

services:
    - docker:dind

stages:
    - build
    - deploy

build:
    stage: build
    script:
        - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
        - docker-compose build
        - docker push $IMAGE:latest
    tags:
        - docker-runner
deploy:
    stage: deploy
    script:
        - apk add --no-cache curl python3 py3-pip
        - pip install awscli
        - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        - aws configure set aws_secret_access_key_id $AWS_SECRET_ACCESS_KEY
        - aws configure set region AWS_DEFAULT_REGION
        - aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE  --force-new-deployment
    tags:
        - docker-runner
