- hosts: localhost
  tasks:
    - name: Sending an email using Ansible
      mail:
        host: smtp-mail.outlook.com
        port: 587
        username: <username>
        from: <emailAddress>
        password: <password>
        to: <emailAddress>
        subject: "{{subject}}"
        body: "{{body}}"